// TOTP secrets are shown only to the account owner, never logged or persisted here.
export async function openSecurity(supa, {onVerified = () => {}, required = false} = {}) {
  document.getElementById('ledger-security')?.remove();
  const dialog=document.createElement('dialog');dialog.id='ledger-security';
  dialog.style.cssText='width:min(440px,90vw);max-height:90vh;overflow:auto;padding:24px;border-radius:20px;background:#101827;color:#fff;border:1px solid #536078';
  dialog.innerHTML='<h2>Account security</h2><p data-status>Loading security settings…</p><div data-factors></div><div data-enroll></div><form data-verify hidden><label>Authenticator code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required aria-label="Authenticator code"></label><button class="btn primary" type="submit">Verify</button></form><p data-note role="status"></p><p style="font-size:13px">Keep a second authenticator on a trusted device for recovery. Losing every authenticator requires an identity-verified recovery review; email alone does not turn protection off.</p><button class="btn ghost" data-add>Add an authenticator</button> <button class="btn ghost" data-close>Close</button>';
  document.body.appendChild(dialog);dialog.showModal();
  const status=dialog.querySelector('[data-status]'),note=dialog.querySelector('[data-note]'),factors=dialog.querySelector('[data-factors]'),setup=dialog.querySelector('[data-enroll]'),form=dialog.querySelector('form');let chosen=null;
  const close=()=>{dialog.close();dialog.remove();};dialog.querySelector('[data-close]').textContent=required?'Sign out':'Close';dialog.querySelector('[data-close]').onclick=async()=>{if(required){await supa.auth.signOut();location.reload();}else close();};if(required)dialog.addEventListener('cancel',e=>e.preventDefault());dialog.addEventListener('close',()=>dialog.remove());
  function choose(id){chosen=id;form.hidden=false;form.elements.code.value='';form.elements.code.focus();}
  async function refresh(){const {data,error}=await supa.auth.mfa.listFactors();if(error)throw error;const verified=(data?.totp||[]).filter(x=>x.status==='verified');const {data:aal,error:ae}=await supa.auth.mfa.getAuthenticatorAssuranceLevel();if(ae)throw ae;status.textContent=verified.length ? (aal.currentLevel==='aal2'?'Two-step verification is active for this session.':'Enter your authenticator code to finish secure sign-in.'):'Two-step verification is required for every Ledger account. Add an authenticator to continue.';factors.replaceChildren();for(const f of verified){const row=document.createElement('div'),b=document.createElement('button');b.className='btn ghost';b.textContent=f.friendly_name||'Authenticator';b.onclick=()=>choose(f.id);row.append(b);if(verified.length>1&&aal.currentLevel==='aal2'){const remove=document.createElement('button');remove.className='btn ghost';remove.textContent='Remove';remove.onclick=async()=>{if(!confirm('Remove this authenticator? Keep your other authenticator available.'))return;const {error}=await supa.auth.mfa.unenroll({factorId:f.id});if(error)note.textContent=error.message;else await refresh();};row.append(remove);}factors.append(row);}if(verified.length&&aal.currentLevel!=='aal2')choose(verified[0].id);}
  dialog.querySelector('[data-add]').onclick=async e=>{e.target.disabled=true;note.textContent='';try{const {data,error}=await supa.auth.mfa.enroll({factorType:'totp',friendlyName:'Authenticator '+new Date().toLocaleDateString()+' '+new Date().toLocaleTimeString()});if(error)throw error;setup.replaceChildren();const p=document.createElement('p');p.textContent='Scan this code in your authenticator, then enter its six-digit code.';const img=document.createElement('img');img.width=220;img.alt='Authenticator setup QR code';img.src=data.totp.qr_code.startsWith('data:image/svg+xml')?data.totp.qr_code:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(data.totp.qr_code);const key=document.createElement('code');key.textContent=data.totp.secret;key.style.overflowWrap='anywhere';setup.append(p,img,key);choose(data.id);}catch(err){note.textContent=err.message;}finally{e.target.disabled=false;}};
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;note.textContent='';try{const code=form.elements.code.value.trim();if(!/^[0-9]{6}$/.test(code)||!chosen)throw Error('Enter the six-digit code from your authenticator.');const {error}=await supa.auth.mfa.challengeAndVerify({factorId:chosen,code});form.elements.code.value='';if(error)throw error;setup.replaceChildren();form.hidden=true;await refresh();note.textContent='Verified. You can now retry the action.';onVerified();if(required)close();}catch(err){note.textContent=err.message;}finally{button.disabled=false;}};
  try{await refresh();}catch(err){status.textContent='Security settings could not load.';note.textContent=err.message;}
}
export async function needsMfa(supa){const {data,error}=await supa.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;if(!data?.currentLevel)throw Error('Account security could not be verified. Please retry.');return data.currentLevel!=='aal2'||data.nextLevel!=='aal2';}
