// TOTP secrets are shown only to the account owner, never logged or persisted here.
export async function openSecurity(supa, {onVerified = () => {}, required = false} = {}) {
  document.getElementById('ledger-security')?.remove();
  const dialog=document.createElement('dialog');dialog.id='ledger-security';
  dialog.style.cssText='width:min(440px,90vw);max-height:90vh;overflow:auto;padding:24px;border-radius:20px;background:#101827;color:#fff;border:1px solid #536078';
  dialog.innerHTML='<h2>Account security</h2><p data-status>Loading security settings…</p><div data-factors></div><div data-enroll></div><form data-verify hidden><label>Authenticator code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required aria-label="Authenticator code"></label><button class="btn primary" type="submit">Verify</button></form><p data-note role="status"></p><p style="font-size:13px" data-recovery>Keep a second authenticator on a trusted device for recovery. Lost every authenticator? Email <a href="mailto:supportteam@heyledger.ai?subject=Lost%20authenticator" style="color:inherit">supportteam@heyledger.ai</a> from your account email — a person verifies your identity by hand before two-step verification is reset (no self-serve bypass). Email alone never turns protection off.</p><button class="btn ghost" data-add>Add an authenticator</button> <button class="btn ghost" data-close>Close</button>';
  document.body.appendChild(dialog);dialog.showModal();
  const status=dialog.querySelector('[data-status]'),note=dialog.querySelector('[data-note]'),factors=dialog.querySelector('[data-factors]'),setup=dialog.querySelector('[data-enroll]'),form=dialog.querySelector('form');let chosen=null;
  const close=()=>{dialog.close();dialog.remove();};dialog.querySelector('[data-close]').textContent=required?'Sign out':'Close';dialog.querySelector('[data-close]').onclick=async()=>{if(required){await supa.auth.signOut();location.reload();}else close();};if(required)dialog.addEventListener('cancel',e=>e.preventDefault());dialog.addEventListener('close',()=>dialog.remove());
  function choose(id){chosen=id;form.hidden=false;form.elements.code.value='';form.elements.code.focus();}
  async function refresh(){const {data,error}=await supa.auth.mfa.listFactors();if(error)throw error;const verified=(data?.totp||[]).filter(x=>x.status==='verified');const {data:aal,error:ae}=await supa.auth.mfa.getAuthenticatorAssuranceLevel();if(ae)throw ae;status.textContent=verified.length ? (aal.currentLevel==='aal2'?'Two-step verification is active for this session.':'Enter your authenticator code to finish secure sign-in.'):'Two-step verification is required for every Ledger account. Add an authenticator to continue.';factors.replaceChildren();for(const f of verified){const row=document.createElement('div'),b=document.createElement('button');b.className='btn ghost';b.textContent=f.friendly_name||'Authenticator';b.onclick=()=>choose(f.id);row.append(b);if(verified.length>1&&aal.currentLevel==='aal2'){const remove=document.createElement('button');remove.className='btn ghost';remove.textContent='Remove';remove.onclick=async()=>{if(!confirm('Remove this authenticator? Keep your other authenticator available.'))return;const {error}=await supa.auth.mfa.unenroll({factorId:f.id});if(error)note.textContent=error.message;else await refresh();};row.append(remove);}factors.append(row);}if(verified.length&&aal.currentLevel!=='aal2')choose(verified[0].id);}
  // Every abandoned "Add" left an unverified factor behind and each one counts
  // toward GoTrue's enrolled-factor cap (audit 01.5). Clear those first — only
  // TOTP rows whose status is unverified; a verified factor is never touched.
  // supabase-js puts verified factors in data.totp; unverified ones are only in data.all.
  async function discardUnverified(){const {data,error}=await supa.auth.mfa.listFactors();if(error)return;for(const f of (data?.all||[]).filter(x=>x.factor_type==='totp'&&x.status==='unverified'&&x.id)){await supa.auth.mfa.unenroll({factorId:f.id}).catch(()=>{});}}
  dialog.querySelector('[data-add]').onclick=async e=>{e.target.disabled=true;note.textContent='';try{await discardUnverified();const {data,error}=await supa.auth.mfa.enroll({factorType:'totp',friendlyName:'Authenticator '+new Date().toLocaleDateString()+' '+new Date().toLocaleTimeString()});if(error)throw error;setup.replaceChildren();const p=document.createElement('p');p.textContent='Scan this code in your authenticator, then enter its six-digit code.';const img=document.createElement('img');img.width=220;img.alt='Authenticator setup QR code';img.src=data.totp.qr_code.startsWith('data:image/svg+xml')?data.totp.qr_code:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(data.totp.qr_code);const key=document.createElement('code');key.textContent=data.totp.secret;key.style.overflowWrap='anywhere';setup.append(p,img,key);choose(data.id);}catch(err){note.textContent=err.message;}finally{e.target.disabled=false;}};
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;note.textContent='';try{const code=form.elements.code.value.trim();if(!/^[0-9]{6}$/.test(code)||!chosen)throw Error('Enter the six-digit code from your authenticator.');const {error}=await supa.auth.mfa.challengeAndVerify({factorId:chosen,code});form.elements.code.value='';if(error)throw error;setup.replaceChildren();form.hidden=true;await refresh();note.textContent='Verified. You can now retry the action.';onVerified();if(required)close();}catch(err){note.textContent=err.message;}finally{button.disabled=false;}};
  if(!required) {
    const section=document.createElement('section');section.style.cssText='margin-top:24px;border-top:1px solid #536078;padding-top:16px';
    const heading=document.createElement('h3');heading.textContent='Business private links';
    const explanation=document.createElement('p');explanation.textContent='Owners and admins can revoke or replace crew, customer, invoice, estimate and tracking links. Replacement stops the old link immediately; it is not sent automatically. Inactive people and void documents stay unavailable.';
    const load=document.createElement('button');load.className='btn ghost';load.textContent='Manage private links';
    const list=document.createElement('div'),message=document.createElement('p');message.setAttribute('role','status');section.append(heading,explanation,load,message,list);dialog.append(section);
    let offset=0;
    async function call(action,body={}) {const {data,error}=await supa.functions.invoke('client-hub',{body:{action:'private-links/'+action,...body}});if(error)throw Error('Private links could not be managed. Owner/admin access and a verified two-factor session are required.');if(data?.error)throw Error(data.error);return data;}
    async function render(reset=true) {load.disabled=true;message.textContent='';try{if(reset){offset=0;list.replaceChildren();}const data=await call('list',{offset});for(const link of data.links){
      const row=document.createElement('div');row.style.cssText='padding:12px 0;border-bottom:1px solid #536078';
      const label=document.createElement('p');const expired=Date.parse(link.expires_at)<=Date.now();label.textContent=link.label+' ('+link.kind+') — '+(link.revoked_at?'Revoked':expired?'Expired':'Expires '+new Date(link.expires_at).toLocaleDateString());
      const revoke=document.createElement('button');revoke.className='btn ghost';revoke.textContent='Revoke';revoke.disabled=!!link.revoked_at;
      const renew=document.createElement('button');renew.className='btn ghost';renew.textContent='Replace link';
      revoke.onclick=async()=>{if(!confirm('Stop this private link from working immediately?'))return;revoke.disabled=true;try{await call('revoke',{kind:link.kind,id:link.record_id});await render();message.textContent='Link revoked.';}catch(e){message.textContent=e.message;revoke.disabled=false;}};
      renew.onclick=async()=>{if(!confirm('Replace this link? The old link will stop working. Share the replacement only with its intended recipient.'))return;renew.disabled=true;try{const data=await call('renew',{kind:link.kind,id:link.record_id});await render();message.textContent='Replacement expires '+new Date(data.link.expires_at).toLocaleDateString()+'. Copy and share securely:';const field=document.createElement('input');field.readOnly=true;field.value=data.url;field.setAttribute('aria-label','Replacement private link');field.style.width='100%';message.append(field);field.select();}catch(e){message.textContent=e.message;renew.disabled=false;}};
      row.append(label,revoke,renew);list.append(row);
    }offset=data.nextOffset;load.textContent=data.more?'Load more links':'Refresh links';load.onclick=()=>render(!data.more);if(!data.links.length&&reset)message.textContent='No private links for this business.';}catch(e){message.textContent=e.message;}finally{load.disabled=false;}}
    load.onclick=()=>render();
  }
  try{await refresh();}catch(err){status.textContent='Security settings could not load.';note.textContent=err.message;}
}
export async function needsMfa(supa){const {data,error}=await supa.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;if(!data?.currentLevel)throw Error('Account security could not be verified. Please retry.');return data.currentLevel!=='aal2'||data.nextLevel!=='aal2';}
